/*
 * J1.java
 *
 * Created on August 21, 2007, 6:14 PM
 */

/**
 *
 * @author  user
 */
public class J1 extends javax.swing.JFrame {
    byte [] b;
    SixBitEnDec s1 = new SixBitEnDec();
    public J1() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdEnc = new javax.swing.JButton();
        cmdDec = new javax.swing.JButton();
        txtIn = new java.awt.TextField();
        txtOut = new java.awt.TextField();
        lblSize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdEnc.setText("Encode");
        cmdEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEncActionPerformed(evt);
            }
        });

        cmdDec.setText("Decode");
        cmdDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDecActionPerformed(evt);
            }
        });

        lblSize.setText("Original Size: 0 bytes  | After Compression : 0 bytes");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtOut, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(cmdEnc)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblSize))
                    .add(cmdDec)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtIn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(txtIn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cmdEnc)
                    .add(lblSize))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtOut, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cmdDec)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDecActionPerformed
        if(b != null && b.length>0)
        {
            txtOut.setText(s1.decode(b,SixBitEnDec.FIVE_BIT));
        }


    }//GEN-LAST:event_cmdDecActionPerformed

    private void cmdEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEncActionPerformed
        String text = txtIn.getText().toLowerCase();
        b = s1.encode(text,SixBitEnDec.FIVE_BIT);
        lblSize.setText("Original Size: "+text.length()+" bytes | After Compression : "+b.length+" bytes");
    }//GEN-LAST:event_cmdEncActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J1().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDec;
    private javax.swing.JButton cmdEnc;
    private javax.swing.JLabel lblSize;
    private java.awt.TextField txtIn;
    private java.awt.TextField txtOut;
    // End of variables declaration//GEN-END:variables
    
}
